language: java

# https://stackoverflow.com/questions/55878548/travis-ci-couldnt-install-openjdk11
dist: xenial

jdk:
  - openjdk11

before_install:
  - mkdir ~/.aws
  - printf "[vertx-s3] \n" >> ~/.aws/credentials
  - printf "aws_secret_access_key = $VERTX_S3_SECRET_KEY \n" >> ~/.aws/credentials
  - printf "aws_access_key_id = $VERTX_S3_ACCESS_KEY \n" >> ~/.aws/credentials

# Overridden because parent project uses maven.test.skip instead of skipTests
install:
  - mvn -q package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V

script:
  - >
    mvn -Ps3it install \
      -Dvertx.s3.bucket="${VERTX_S3_BUCKET}-${TRAVIS_JDK_VERSION}" \
      -Dorg.slf4j.simpleLogger.log.net.sourceforge.pmd=error \
      -Dvertx.s3.access_key="${VERTX_S3_ACCESS_KEY}" -Dvertx.s3.secret_key="${VERTX_S3_SECRET_KEY}"


after_success:
  - mvn org.jacoco:jacoco-maven-plugin:report
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml
  - chmod 755 src/main/tools/travis/*
  - src/main/tools/travis/get_build_key $encrypted_f9b802c36f4f_key $encrypted_f9b802c36f4f_iv
  - src/main/tools/travis/deploy

cache:
  directories:
  - $HOME/.m2

# The only branch we build on is master; all other builds are done on PRs to master
branches:
  only:
  - master

notifications:
  email:
    recipients:
    - ksclarke@ksclarke.io
    on_failure: change
    on_success: change

sudo: false
