language: java

jdk:
  - openjdk11

services:
  - docker

before_install:
  - mkdir $HOME/.aws
  - printf "[default] \n" >> $HOME/.aws/credentials
  - printf "aws_secret_access_key = $VERTX_S3_SECRET_KEY \n" >> ~/.aws/credentials
  - printf "aws_access_key_id = $VERTX_S3_ACCESS_KEY \n" >> ~/.aws/credentials
  - printf "[vertx-s3] \n" >> $HOME/.aws/credentials
  - printf "aws_secret_access_key = $VERTX_S3_SECRET_KEY \n" >> ~/.aws/credentials
  - printf "aws_access_key_id = $VERTX_S3_ACCESS_KEY \n" >> ~/.aws/credentials

# Overridden because parent project uses maven.test.skip instead of skipTests
install:
  - mvn -s src/test/resources/settings.xml -q package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V

script:
  - >
    mvn -B -s src/test/resources/settings.xml -Ps3it help:active-profiles verify \
      -Dvertx.s3.bucket="${VERTX_S3_BUCKET}-${TRAVIS_JDK_VERSION}" \
      -Dorg.slf4j.simpleLogger.log.net.sourceforge.pmd=error \
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

after_success:
  - >
    mvn -s src/test/resources/settings.xml site -Djava.util.logging.config.file=src/test/resources/logging.properties \
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn site:deploy -B
  - chmod 755 src/main/tools/travis/*
  - src/main/tools/travis/get_build_key $encrypted_f9b802c36f4f_key $encrypted_f9b802c36f4f_iv
  - src/main/tools/travis/deploy

cache:
  directories:
  - $HOME/.m2

# The only branch we build on is main; all other builds are done on PRs to main
branches:
  only:
  - main

notifications:
  email:
    recipients:
    - ksclarke@ksclarke.io
    on_failure: change
    on_success: change
