language: java

# Deployment happens on openjdk11
jdk:
  - openjdk8
  - openjdk11

# Install AWS CLI to get the credentials file
before_install:
  - mkdir ~/.aws
  - printf "[vertx-s3] \n" >> ~/.aws/credentials
  - printf "aws_secret_access_key = $VERTX_S3_SECRET_KEY \n" >> ~/.aws/credentials
  - printf "aws_access_key_id = $VERTX_S3_ACCESS_KEY \n" >> ~/.aws/credentials
  - >
    openssl aes-256-cbc -K $encrypted_f9b802c36f4f_key -iv $encrypted_f9b802c36f4f_iv \
      -in src/main/resources/build-key.gpg.enc -out src/main/resources/build-key.gpg -d


# Overridden because parent project uses maven.test.skip instead of skipTests
install: mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V

script:
  - >
    mvn -Ps3it install -Dvertx.s3.bucket="${VERTX_S3_BUCKET}-${TRAVIS_JDK_VERSION}" \
      -Dvertx.s3.access_key="${VERTX_S3_ACCESS_KEY}" -Dvertx.s3.secret_key="${VERTX_S3_SECRET_KEY}"
  - >
    mvn pmd:pmd pmd:check

after_success:
  - >
    mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml \
      -DprojectToken="${PROJECT_TOKEN}" -DapiToken="${API_TOKEN}"
  - >
    src/main/tools/travis/deploy

cache:
  directories:
  - $HOME/.m2

# We want all PRs built but only merges on master branch
#  However, when we first create a new project, we need to comment this out
branches:
  only:
  - master

notifications:
  email:
    recipients:
    - ksclarke@ksclarke.io
    on_failure: change
    on_success: change
  irc:
    channels:
    - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always

sudo: false
