#! /bin/bash

#
# A simple script to perform a release. It can be run locally or from a CI server.
# From CI, a settings.xml file must be supplied.
#

# We can supply a settings.xml file for custom settings
if [ -z "$1" ]; then
  mvn -Dmaven.test.skip=true clean deploy -P release
else
  mvn -Dmaven.test.skip=true clean deploy -P release -s "$1"
fi
