name: Maven Release

# Performs a Maven release using JDK 11 when a new GitHub release has been published
on:
  release:
    types: [ published ]

jobs:

  publish:
    name: Maven Artifact Publisher (JDK 11)
    runs-on: ubuntu-latest

    env:
      AUTORELEASE_ARTIFACT: ${{ secrets.AUTORELEASE_ARTIFACT }}
      SKIP_JAR_DEPLOYMENT: ${{ secrets.SKIP_JAR_DEPLOYMENT }}
      MAVEN_CACHE_KEY: ${{ secrets.MAVEN_CACHE_KEY }}

    steps:
      - name: Check out source code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2
      
      - name: Install JDK 11
        uses: actions/setup-java@0aa6f2a84f8634ac1a1bd81dfdf6d5aab98c70f1 # v3
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Set up Maven cache
        uses: actions/cache@0781355a23dac32fd3bac414512f4b903437991a # v2
        if: ${{ env.MAVEN_CACHE_KEY }}
        with:
          path: ~/.m2
          key: freelibrary-cache-${{ secrets.MAVEN_CACHE_KEY }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: freelibrary-cache-${{ secrets.MAVEN_CACHE_KEY }}-

      - name: Set autorelease config
        if: env.AUTORELEASE_ARTIFACT == null
        run: echo "AUTORELEASE_ARTIFACT=false" >> $GITHUB_ENV

      - name: Set Jar deployment config
        if: env.SKIP_JAR_DEPLOYMENT == null
        run: echo "SKIP_JAR_DEPLOYMENT=false" >> $GITHUB_ENV

      - name: Release with Maven
        uses: samuelmeuli/action-maven-publish@201a45a3f311b2ee888f252ba9f4194257545709 # v1.4.0
        with:
          gpg_private_key: ${{ secrets.BUILD_KEY }}
          gpg_passphrase: ${{ secrets.BUILD_PASSPHRASE }}
          nexus_username: ${{ secrets.SONATYPE_USERNAME }}
          nexus_password: ${{ secrets.SONATYPE_PASSWORD }}
          maven_profiles: "release"
          maven_args: >
            -Drevision=${{ github.event.release.tag_name }} -DautoReleaseAfterClose=${{ env.AUTORELEASE_ARTIFACT }}
            -ntp -Dorg.slf4j.simpleLogger.log.net.sourceforge.pmd=error
            -DskipNexusStagingDeployMojo=${{ env.SKIP_JAR_DEPLOYMENT }}
